[tool.autopep8]
max_line_length = 120
ignore = ["E501", "W6"]

[tool.flake8]
max-line-length = 120

[tool.pycodestyle]
max_line_length = 120
ignore = ["E501", "W6"]

[tool.pydocstyle]
max-line-length = 80

[tool.pyright]
exclude = [
	"**/node_modules",
	"**/__pycache__",
	"**/.*",
	".venv",
	"tmp",
]

[project]
name = "vscode-keynav"
version = "0.0.0"
description = "Shared library for vscode-keyboard-navigation tools"
authors = [ { name = "Joseph Tingiris", email = "joseph.tingiris@gmail.com" } ]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
